### ISSUE TITLE
Food list needs more lasagna

### ISSUE THREAD

**Issue by LXShades** [FruitBats/ourfavorites#7]
This is a big problem, I'm very disappointed in you all, and humanity in general

--Garfield the Cat

**Comment by LXShades** [comment]
I looked further into your issue and found that it does indeed exist. However, I have procrastination to do, so instead have corrected your spelling error ('lasagna') and I'll do the rest tomorrow.

--Bagpuss

**Comment by HoaxShark** [comment]
Also on further inspection, no Fern's in the list either. You are all disgusting.

--Garfield the cat

**Comment by TMGilchrist** [comment]
I have added Lasagna to favorite-foods.txt as requested. This issue will now be closed
